server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identityserv/**
          filters:
            - RewritePath=/identityserv/(?<path>.*), /$\{path}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orderserv/**
          filters:
            - RewritePath=/orderserv/(?<path>.*), /$\{path}
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/paymentserv/**
          filters:
            - RewritePath=/paymentserv/(?<path>.*), /$\{path}
        - id: resturant-service
          uri: lb://resturant-service
          predicates:
            - Path=/resturantserv/**
          filters:
            - RewritePath=/resturantserv/(?<path>.*), /$\{path}
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stockserv/**
          filters:
            - RewritePath=/stockserv/(?<path>.*), /$\{path}
        - id: utility-service
          uri: lb://utility-service
          predicates:
            - Path=/utilityserv/**
          filters:
            - RewritePath=/utilityserv/(?<path>.*), /$\{path}
    #management:
#  endpoint:
#    gateway:
#      enabled: true