pipeline {
    agent any
    tools {
        maven 'maven' // Maven tool đã cấu hình trong Jenkins
    }
    environment {
        GLOBAL_ENVIRONMENT = 'main'
        APP_ENV = 'default'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building for main environment...'
                script {
                    sh 'cd eureka-server && mvn clean package -DskipTests'
                }
            }
        }
        stage('Code Analysis') {
            steps {
                echo "Running SonarQube analysis"
                script {
                    withSonarQubeEnv('sonarsql') {
                        dir('eureka-server') {
                            sh 'mvn sonar:sonar'
                        }
                    }
                }
            }
        }
        stage('Publish Image') {
            steps {
                echo "Publishing Docker image for main environment..."
                script {
                    sh 'cd eureka-server && docker build -t huuphat125/eureka-server .'
                    withCredentials([string(credentialsId: 'docker_cred', variable: 'dockerpwd')]) {
                        sh '''
                            echo "$dockerpwd" | docker login -u huuphat125 --password-stdin
                            docker push huuphat125/eureka-server
                        '''
                    }
                    echo "Image published successfully"
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                echo "Deploying to Kubernetes (Minikube)"
                script {
                    kubeconfig(
                        credentialsId: 'kube_config',
                        serverUrl: 'https://127.0.0.1:55277',
                        caCertificate: ''
                    ) {
                        sh '''
                            kubectl version --client
                            kubectl apply -f eureka-server/deployment.yaml --namespace=jiffymeals
                            kubectl get pods --namespace=jiffymeals
                            kubectl get svc --namespace=jiffymeals
                        '''
                    }
                    echo "Deployment to Kubernetes was successful"
                }
            }
        }
    }
}
